-- ============================================================================
-- Mundial 2026 - Quiniela de predicciones
-- Migración 0001: esquema, RLS (deny-by-default), vistas y triggers.
-- Toda la autorización vive aquí (no en el cliente). Ver DEPLOY.md.
-- ============================================================================

-- Extensiones (gen_random_uuid)
create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- Tipos enumerados
-- ----------------------------------------------------------------------------
do $$ begin
  create type match_stage as enum ('group','r32','r16','qf','sf','third','final');
exception when duplicate_object then null; end $$;

do $$ begin
  create type match_status as enum ('scheduled','live','finished');
exception when duplicate_object then null; end $$;

do $$ begin
  create type member_role as enum ('admin','member');
exception when duplicate_object then null; end $$;

do $$ begin
  create type invitation_status as enum ('pending','accepted');
exception when duplicate_object then null; end $$;

-- ----------------------------------------------------------------------------
-- Catálogo del torneo (datos de referencia; escritura solo vía service_role)
-- ----------------------------------------------------------------------------
create table if not exists public.stadiums (
  id          serial primary key,
  name        text not null,
  city        text not null,
  country     text not null
);

create table if not exists public.teams (
  id            serial primary key,
  code          text not null unique,          -- p. ej. 'MEX'
  name          text not null,
  flag_emoji    text,
  group_letter  char(1)                          -- A..L; null si solo placeholder
);

create table if not exists public.matches (
  id              bigint generated by default as identity primary key,
  external_id     text unique,                   -- id de la fuente de marcadores
  stage           match_stage not null,
  group_letter    char(1),                       -- solo fase de grupos
  matchday        int,                           -- jornada (orden dentro de fase)
  home_team_id    int references public.teams(id),
  away_team_id    int references public.teams(id),
  home_placeholder text,                          -- 'Ganador Grupo A', etc. (knockout)
  away_placeholder text,
  stadium_id      int references public.stadiums(id),
  kickoff_at      timestamptz not null,
  status          match_status not null default 'scheduled',
  home_score      int check (home_score >= 0),
  away_score      int check (away_score >= 0),
  updated_at      timestamptz not null default now()
);
create index if not exists matches_kickoff_idx on public.matches (kickoff_at);
create index if not exists matches_stage_idx on public.matches (stage);

-- ----------------------------------------------------------------------------
-- Perfiles de usuario (1:1 con auth.users)
-- ----------------------------------------------------------------------------
create table if not exists public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url   text,
  description  text,
  created_at   timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- Grupos de apuestas
-- ----------------------------------------------------------------------------
create table if not exists public.bet_groups (
  id          uuid primary key default gen_random_uuid(),
  name        text not null check (char_length(name) between 1 and 80),
  description text check (char_length(description) <= 500),
  creator_id  uuid not null references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now()
);
create index if not exists bet_groups_creator_idx on public.bet_groups (creator_id);

create table if not exists public.group_members (
  id        uuid primary key default gen_random_uuid(),
  group_id  uuid not null references public.bet_groups(id) on delete cascade,
  user_id   uuid not null references auth.users(id) on delete cascade,
  role      member_role not null default 'member',
  joined_at timestamptz not null default now(),
  unique (group_id, user_id)
);
create index if not exists group_members_user_idx on public.group_members (user_id);
create index if not exists group_members_group_idx on public.group_members (group_id);

create table if not exists public.group_invitations (
  id            uuid primary key default gen_random_uuid(),
  group_id      uuid not null references public.bet_groups(id) on delete cascade,
  invited_email text not null,                  -- siempre en minúsculas, dominio gmail
  invited_by    uuid not null references auth.users(id) on delete cascade,
  status        invitation_status not null default 'pending',
  created_at    timestamptz not null default now(),
  unique (group_id, invited_email)
);
create index if not exists group_invitations_email_idx on public.group_invitations (invited_email);

-- ----------------------------------------------------------------------------
-- Predicciones (por grupo, por usuario, por partido)
-- ----------------------------------------------------------------------------
create table if not exists public.predictions (
  id         uuid primary key default gen_random_uuid(),
  group_id   uuid not null references public.bet_groups(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  match_id   bigint not null references public.matches(id) on delete cascade,
  home_score int not null check (home_score between 0 and 30),
  away_score int not null check (away_score between 0 and 30),
  updated_at timestamptz not null default now(),
  unique (group_id, user_id, match_id)
);
create index if not exists predictions_group_user_idx on public.predictions (group_id, user_id);

-- Envío/bloqueo de una fase por usuario y grupo (gobierna visibilidad de ajenas)
create table if not exists public.phase_submissions (
  id           uuid primary key default gen_random_uuid(),
  group_id     uuid not null references public.bet_groups(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  stage        match_stage not null,
  submitted_at timestamptz not null default now(),
  unique (group_id, user_id, stage)
);

-- ----------------------------------------------------------------------------
-- Configuración (intervalo de sync, etc.). Solo accesible por service_role.
-- ----------------------------------------------------------------------------
create table if not exists public.app_config (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- Funciones helper (SECURITY DEFINER para evitar recursión de RLS)
-- ============================================================================
create or replace function public.my_email()
returns text language sql stable security definer set search_path = public, pg_temp as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

create or replace function public.is_member(p_group uuid)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists (
    select 1 from public.group_members
    where group_id = p_group and user_id = auth.uid()
  );
$$;

create or replace function public.is_creator(p_group uuid)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists (
    select 1 from public.bet_groups
    where id = p_group and creator_id = auth.uid()
  );
$$;

create or replace function public.shares_group(p_other uuid)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists (
    select 1
    from public.group_members a
    join public.group_members b on a.group_id = b.group_id
    where a.user_id = auth.uid() and b.user_id = p_other
  );
$$;

create or replace function public.has_pending_invite(p_group uuid)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists (
    select 1 from public.group_invitations
    where group_id = p_group and invited_email = public.my_email() and status = 'pending'
  );
$$;

-- ¿El viewer puede ver predicciones ajenas de este partido en este grupo?
-- Solo si ya envió la fase del partido en ese grupo.
create or replace function public.can_see_prediction(p_group uuid, p_match bigint)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists (
    select 1
    from public.matches m
    join public.phase_submissions ps
      on ps.group_id = p_group and ps.user_id = auth.uid() and ps.stage = m.stage
    where m.id = p_match
  );
$$;

-- ¿Se puede crear/editar una predicción? Solo si el partido no ha iniciado
-- y la fase no ha sido enviada por el usuario en ese grupo.
create or replace function public.can_edit_prediction(p_group uuid, p_match bigint)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists (
    select 1
    from public.matches m
    where m.id = p_match
      and m.kickoff_at > now()
      and not exists (
        select 1 from public.phase_submissions ps
        where ps.group_id = p_group and ps.user_id = auth.uid() and ps.stage = m.stage
      )
  );
$$;

-- ============================================================================
-- Trigger: crear profile al registrarse
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Trigger: mantener updated_at
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists predictions_touch on public.predictions;
create trigger predictions_touch before update on public.predictions
  for each row execute function public.touch_updated_at();

drop trigger if exists matches_touch on public.matches;
create trigger matches_touch before update on public.matches
  for each row execute function public.touch_updated_at();

-- ============================================================================
-- Vistas de cálculo (volumen pequeño; sin triggers de puntaje)
-- ============================================================================
-- Puntos por predicción: exacto = 3, acierta resultado = 1, else 0
create or replace view public.v_prediction_points as
  select
    p.id        as prediction_id,
    p.group_id,
    p.user_id,
    p.match_id,
    m.stage,
    case
      when m.status = 'finished'
           and p.home_score = m.home_score and p.away_score = m.away_score then 3
      when m.status = 'finished'
           and sign(p.home_score - p.away_score) = sign(m.home_score - m.away_score) then 1
      else 0
    end as points
  from public.predictions p
  join public.matches m on m.id = p.match_id;

-- Ranking por grupo (suma de puntos + posición)
create or replace view public.v_group_ranking as
  with totals as (
    select gm.group_id, gm.user_id, coalesce(sum(vp.points), 0) as total_points
    from public.group_members gm
    left join public.v_prediction_points vp
      on vp.group_id = gm.group_id and vp.user_id = gm.user_id
    group by gm.group_id, gm.user_id
  )
  select
    group_id,
    user_id,
    total_points,
    rank() over (partition by group_id order by total_points desc) as position
  from totals;

-- Las vistas se ejecutan con permisos del invocador (security_invoker) para
-- respetar las RLS de las tablas base.
alter view public.v_prediction_points set (security_invoker = on);
alter view public.v_group_ranking set (security_invoker = on);

-- ============================================================================
-- RLS: activar en TODAS las tablas (deny-by-default) y políticas explícitas
-- ============================================================================
alter table public.stadiums          enable row level security;
alter table public.teams             enable row level security;
alter table public.matches           enable row level security;
alter table public.profiles          enable row level security;
alter table public.bet_groups        enable row level security;
alter table public.group_members     enable row level security;
alter table public.group_invitations enable row level security;
alter table public.predictions       enable row level security;
alter table public.phase_submissions enable row level security;
alter table public.app_config        enable row level security;

-- Catálogo: lectura para autenticados; escritura solo service_role (sin política)
create policy "stadiums readable" on public.stadiums for select to authenticated using (true);
create policy "teams readable"    on public.teams    for select to authenticated using (true);
create policy "matches readable"  on public.matches  for select to authenticated using (true);

-- profiles
create policy "profiles select own or shared" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.shares_group(id));
create policy "profiles insert own" on public.profiles
  for insert to authenticated with check (id = auth.uid());
create policy "profiles update own" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- bet_groups
create policy "groups select member or creator" on public.bet_groups
  for select to authenticated
  using (creator_id = auth.uid() or public.is_member(id));
create policy "groups insert as creator" on public.bet_groups
  for insert to authenticated with check (creator_id = auth.uid());
create policy "groups update by creator" on public.bet_groups
  for update to authenticated using (creator_id = auth.uid()) with check (creator_id = auth.uid());
create policy "groups delete by creator" on public.bet_groups
  for delete to authenticated using (creator_id = auth.uid());

-- group_members
create policy "members select within group" on public.group_members
  for select to authenticated
  using (user_id = auth.uid() or public.is_member(group_id));
-- Alta: el creador se agrega a sí mismo (admin) o un invitado acepta su invitación
create policy "members insert self if creator or invited" on public.group_members
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and (public.is_creator(group_id) or public.has_pending_invite(group_id))
  );
-- Baja: solo el creador puede eliminar miembros (y no a sí mismo)
create policy "members delete by creator" on public.group_members
  for delete to authenticated
  using (public.is_creator(group_id) and user_id <> auth.uid());

-- group_invitations
create policy "invites select creator or invitee" on public.group_invitations
  for select to authenticated
  using (public.is_creator(group_id) or invited_email = public.my_email());
create policy "invites insert by creator only" on public.group_invitations
  for insert to authenticated
  with check (public.is_creator(group_id) and invited_by = auth.uid());
create policy "invites update invitee or creator" on public.group_invitations
  for update to authenticated
  using (invited_email = public.my_email() or public.is_creator(group_id))
  with check (invited_email = public.my_email() or public.is_creator(group_id));
create policy "invites delete by creator" on public.group_invitations
  for delete to authenticated using (public.is_creator(group_id));

-- predictions
create policy "predictions select own or visible" on public.predictions
  for select to authenticated
  using (
    user_id = auth.uid()
    or (public.is_member(group_id) and public.can_see_prediction(group_id, match_id))
  );
create policy "predictions insert own editable" on public.predictions
  for insert to authenticated
  with check (
    user_id = auth.uid()
    and public.is_member(group_id)
    and public.can_edit_prediction(group_id, match_id)
  );
create policy "predictions update own editable" on public.predictions
  for update to authenticated
  using (user_id = auth.uid() and public.can_edit_prediction(group_id, match_id))
  with check (user_id = auth.uid() and public.can_edit_prediction(group_id, match_id));
create policy "predictions delete own editable" on public.predictions
  for delete to authenticated
  using (user_id = auth.uid() and public.can_edit_prediction(group_id, match_id));

-- phase_submissions
create policy "submissions select within group" on public.phase_submissions
  for select to authenticated
  using (user_id = auth.uid() or public.is_member(group_id));
create policy "submissions insert own" on public.phase_submissions
  for insert to authenticated
  with check (user_id = auth.uid() and public.is_member(group_id));

-- app_config: sin políticas => inaccesible a clientes (solo service_role).
